user:
  server-url: test-url

spring:
  datasource:
    username: root
    password: 333
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8

mybatis-plus:
  mapper-locations: [classpath*:/com/obitosnn/**/mapper/**/*.xml]

